POST http://localhost:3000/v1/student
Content-Type: application/json
tenantid: tenanta
traceparent: 12345
Authorization: bearer Token

{
  "name": "Arif Shaikh",
  "adhaar": "1234 1234 1234 ",
  "school": "E Learning Online"
}
